# Generated by Django 4.0.5 on 2022-12-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_language',
            field=models.CharField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('Java', 'Java'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('SQL', 'SQL'), ('C#', 'C#'), ('C', 'C'), ('C++', 'C++'), ('TypeScript', 'TypeScript'), ('PHP', 'PHP'), ('R', 'R'), ('Bash/Shell', 'Bash/Shell'), ('Go', 'Go'), ('Swift', 'Swift'), ('all', 'all')], default='all', max_length=15),
        ),
    ]
